application: openlayerer
version: 3
runtime: python
api_version: 1

handlers:
- url: /style
  static_dir: style

- url: /recipes
  static_dir: recipes 

- url: /js
  static_dir: js

- url: .*
  script: main.py
